server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json
  undertow:
    worker-threads: 128
  error:
    whitelabel.enabled: true
  jsp-servlet:
    registered: false

spring:
  profiles:
    active: 'default'
  main:
    web-environment: false
    banner-mode: "off"
  jmx:
    enabled: false
  freemarker:
    enabled: false
  groovy:
    template:
      enabled: false
  mobile:
    sitepreference:
      enabled: false
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:mem:inmemorydbname
    driver-class: org.h2.Driver
    initialize: true

application:
  app_name: @project.artifactId@
  app_version: @project.version@.@timestamp@

security:
  security_basicauth_enabled: false
  security_jwtauth_enabled: true
  security_jwtauth_secretkey: WebTemplateSecretKey!
  security_jwtauth_minexpirationtime: 3600