server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json
  undertow:
    worker-threads: 128

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    lp.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{50} - %msg%n"
    
spring:
  main:
    banner-mode: "off"
  jmx: 
    enabled: false
  freemarker: 
    enabled: false
  groovy: 
    template: 
      enabled: false
  thymeleaf: 
    cache: false
  datasource:
    url: jdbc:h2:mem:inmemorydbname
    driver-class: org.h2.Driver
    initialize: true
    
application:
  app_name: @project.artifactId@
  app_version: @project.version@.@timestamp@

security:
  security_basicauth_enabled: false
  security_jwtauth_enabled: true
  security_jwtauth_secretkey: WebTemplateSecretKey!
  security_jwtauth_minexpirationtime: 3600