server:
  port: 8080
  http2:
    enabled: true
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json
  undertow:
    worker-threads: 128
  error:
    whitelabel.enabled: true
  jsp-servlet:
    registered: false

spring:
  profiles:
    active: 'default'
  main:
    web-environment: false
    banner-mode: "off"
  jmx:
    enabled: false
  freemarker:
    enabled: false
  groovy:
    template:
      enabled: false
  mobile:
    sitepreference:
      enabled: false
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:mem:inmemorydbname
    driver-class: org.h2.Driver
    initialize: false
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: none
  #if (${withCache} == 'Y')
  cache:
    caffeine:
      spec:
        maximumSize=200,expireAfterWrite=10m
  #end

application:
  app_name: @project.name@
  app_description: @project.description@
  app_version: @project.version@
  app_timestamp: @timestamp@
#if (${withSecurity} == 'Y')

security:
  security_basicauth_enabled: false
  security_jwtauth_enabled: false
  security_jwtauth_secretkey: WebTemplateSecretKey!
  security_jwtauth_minexpirationtime: 3600
#end