server:
    port: 8080
    servlet:
      context-path: /WebServerTemplate/
    compression:
      enabled: true
      mime-types: application/json

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    lp.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{50} - %msg%n"
    
spring:
  main:
    banner-mode: "off"
  jmx: 
    enabled: false
  freemarker: 
    enabled: false
  groovy: 
    template: 
      enabled: false
  thymeleaf: 
    cache: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:h2:mem:inmemorydbname
    driver-class: org.h2.Driver
    initialize: true
    
application:
  app_name: #project.artifactId#
  app_version: #project.version#.#buildNumber#

security:
  security_basicauth_enabled:false
  security_jwtauth_enabled:true
  security_jwtauth_secretkey:WebTemplateSecretKey!
  security_jwtauth_minexpirationtime:3600

sentry:
  sentry_enabled:false
  dsn:https://public:private@host:port/1