pipeline {

  environment {

    // Project data
    projectName = '${artifactId}'
	#if (${javaVersion} == '17')
	jdkVersion = 'Open JDK 17'
	#end
	#if (${javaVersion} == '21')
    jdkVersion = 'OpenJDK-21'
    #end
	#if (${javaVersion} == '11')
	jdkVersion = 'OpenJDK-11'
	#end
	#if (${javaVersion} == '8')
	jdkVersion = 'OpenJDK-8'
	#end

    // CI/CD data
    cicdJob = 'Template - Maven Project'

  }

  agent any

  stages {

    stage('Defining environment') {
      steps {
        script {
          echo "Defining environment"
          env.GIT_URL = sh(returnStdout: true, script: 'git config remote.origin.url').trim()
          echo "Setting git url as ${env.GIT_URL}"
          echo "Setting env as ${env.GIT_BRANCH}"
        }
      }
    }

    stage('Run CI/CD') {
      steps {
        build job: cicdJob, parameters: [
          // Mandatory parameters
          [$class: 'StringParameterValue', name: 'projectName', value: projectName],
          [$class: 'StringParameterValue', name: 'gitUrl', value: env.GIT_URL],
          [$class: 'StringParameterValue', name: 'gitBranch', value: env.GIT_BRANCH],
          // Optional parameters
          [$class: 'StringParameterValue', name: 'jdkVersion', value: jdkVersion]
          // Kubernetes data...
          // Remote GIT data...
          // VM Data
        ]
      }
    }

  }

}
